import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const expertImages = [
  "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200",
  "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200",
  "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=200",
  "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200",
  "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=200",
];

function makeRoomLayouts(capacity: number, type: string) {
  const factor = (pct: number) => Math.round(capacity * pct);
  if (type === "conference_center") {
    return JSON.stringify([
      { name: "Main Hall", theater: capacity, classroom: factor(0.6), uShape: factor(0.2), boardroom: factor(0.15), cabaret: factor(0.5), reception: factor(1.2) },
      { name: "Breakout Room A", theater: factor(0.2), classroom: factor(0.12), uShape: factor(0.08), boardroom: factor(0.06), cabaret: factor(0.1), reception: factor(0.25) },
      { name: "Breakout Room B", theater: factor(0.15), classroom: factor(0.1), uShape: factor(0.06), boardroom: factor(0.05), cabaret: factor(0.08), reception: factor(0.2) },
    ]);
  }
  if (type === "meeting_room") {
    return JSON.stringify([
      { name: "Main Room", theater: capacity, classroom: factor(0.65), uShape: factor(0.35), boardroom: factor(0.3), cabaret: factor(0.5), reception: factor(1.2) },
    ]);
  }
  return JSON.stringify([
    { name: "Main Space", theater: capacity, classroom: factor(0.6), uShape: factor(0.25), boardroom: factor(0.2), cabaret: factor(0.45), reception: factor(1.3) },
    { name: "Secondary Room", theater: factor(0.25), classroom: factor(0.15), uShape: factor(0.1), boardroom: factor(0.08), cabaret: factor(0.12), reception: factor(0.3) },
  ]);
}

function makeFacilities(amenities: string[]) {
  const categories: { category: string; items: string[] }[] = [];
  const meeting: string[] = ["Free high-speed WiFi", "Climate control"];
  const tech: string[] = [];
  const comfort: string[] = ["Reception desk", "Coat check"];
  const access: string[] = [];

  if (amenities.includes("projector")) { tech.push("HD Projector & screen"); meeting.push("Presentation clicker"); }
  if (amenities.includes("av_equipment")) { tech.push("Professional sound system", "Wireless microphones", "Large LED displays"); }
  if (amenities.includes("video_conferencing")) { tech.push("Video conferencing (Zoom/Teams)", "HD webcam setup"); }
  if (amenities.includes("whiteboard")) { meeting.push("Whiteboards & markers", "Flip charts"); }
  if (amenities.includes("catering")) { comfort.push("On-site catering available", "Coffee & tea station", "Water service"); }
  if (amenities.includes("kitchen")) { comfort.push("Fully equipped kitchen", "Refrigerator"); }
  if (amenities.includes("parking")) { access.push("On-site parking available"); }
  if (amenities.includes("accessibility")) { access.push("Wheelchair accessible", "Elevator access", "Accessible restrooms"); }
  if (amenities.includes("outdoor_space")) { comfort.push("Outdoor terrace/garden"); }
  if (amenities.includes("natural_light")) { comfort.push("Abundant natural light"); }
  if (amenities.includes("breakout_rooms")) { meeting.push("Multiple breakout rooms"); }

  categories.push({ category: "Meeting Essentials", items: meeting });
  if (tech.length) categories.push({ category: "Technology", items: tech });
  categories.push({ category: "Comfort & Catering", items: comfort });
  if (access.length) categories.push({ category: "Access & Parking", items: access });

  return JSON.stringify(categories);
}

const venues = [
  // AMSTERDAM (6)
  {
    name: "Het Conferentiecentrum Amsterdam",
    slug: "het-conferentiecentrum-amsterdam",
    city: "Amsterdam",
    address: "Europaplein 24, 1078 GZ Amsterdam",
    description:
      "A premier conference center in the heart of Amsterdam's business district. Featuring state-of-the-art audiovisual technology, flexible room configurations, and panoramic city views. Ideal for large corporate events, product launches, and international conferences. Full catering services available with a dedicated event coordinator.",
    shortDescription: "Premier conference center with panoramic city views in Amsterdam's business district",
    capacity: 350,
    pricePerDay: 3500,
    pricePerHalfDay: 2100,
    amenities: ["wifi", "catering", "projector", "av_equipment", "breakout_rooms", "parking", "accessibility", "video_conferencing"],
    images: [
      "https://images.unsplash.com/photo-1505373877841-8d25f7d46678?w=800",
      "https://images.unsplash.com/photo-1497366216548-37526070297c?w=800",
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800",
    ],
    venueType: "conference_center",
    rating: 4.8,
    latitude: 52.3389,
    longitude: 4.8913,
    transportInfo: "5-minute walk from Amsterdam RAI station (Metro 52). Tram 4 stops directly in front. Amsterdam Centraal is 15 minutes by metro.",
    parkingInfo: "Underground parking garage with 200 spaces. €25/day per vehicle. Electric vehicle charging available.",
    meetingExpertName: "Sophie van den Berg",
    meetingExpertRole: "Senior Event Coordinator",
    meetingExpertImage: expertImages[0],
    phoneNumber: "0800 - 250 60 60",
    email: "events@conferentiecentrum-amsterdam.nl",
    sustainabilityInfo: "We offset CO2 emissions for every event. Solar panels provide 40% of our energy. Catering uses locally sourced, seasonal ingredients.",
    termsAndConditions: "Cancellation up to 14 days before: full refund. 7-14 days: 50% refund. Less than 7 days: no refund. Minimum 2 hours booking. Setup and breakdown time included. Damage deposit of €500 required for events over 200 persons.",
  },
  {
    name: "Grachtenboot De Vergadering",
    slug: "grachtenboot-de-vergadering",
    city: "Amsterdam",
    address: "Prinsengracht 280, 1016 HJ Amsterdam",
    description:
      "A unique meeting experience aboard a beautifully restored canal boat on the Prinsengracht. This intimate floating venue offers a truly Dutch atmosphere with modern amenities. Perfect for creative brainstorms, team building sessions, and exclusive client meetings. Cruise through Amsterdam's iconic canals while you meet.",
    shortDescription: "Unique floating meeting venue on Amsterdam's historic Prinsengracht canal",
    capacity: 28,
    pricePerDay: 850,
    pricePerHalfDay: 500,
    amenities: ["wifi", "catering", "projector", "natural_light", "outdoor_space"],
    images: [
      "https://images.unsplash.com/photo-1534351590666-13e3e96b5017?w=800",
      "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800",
      "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800",
    ],
    venueType: "unique_venue",
    rating: 4.9,
    latitude: 52.3667,
    longitude: 4.8818,
    transportInfo: "Board at Prinsengracht 280, near Westerkerk. 10-minute walk from Amsterdam Centraal. Tram 13, 17 stop at Westermarkt.",
    parkingInfo: "No on-site parking. Nearest public parking: Europarking (5 min walk), €5/hour.",
    meetingExpertName: "Jan de Vries",
    meetingExpertRole: "Captain & Event Host",
    meetingExpertImage: expertImages[1],
    phoneNumber: "020 - 555 1234",
    email: "ahoy@grachtenboot-vergadering.nl",
    sustainabilityInfo: "Electric-powered vessel with zero emissions. All catering uses biodegradable packaging.",
    termsAndConditions: "Weather-dependent sailing routes. Cancellation up to 7 days: full refund. 3-7 days: 50%. Less than 3 days: no refund. Maximum 28 persons for safety. Life jackets provided.",
  },
  {
    name: "Museum Event Hall Amsterdam",
    slug: "museum-event-hall-amsterdam",
    city: "Amsterdam",
    address: "Museumstraat 1, 1071 XX Amsterdam",
    description:
      "Host your event surrounded by world-class art in this stunning museum venue. The grand hall features soaring ceilings, natural light through ornate skylights, and a sense of prestige that elevates any gathering. Suitable for gala dinners, award ceremonies, and high-profile corporate events. Exhibition spaces can be incorporated into your event program.",
    shortDescription: "Prestigious museum venue with soaring ceilings and world-class art surroundings",
    capacity: 200,
    pricePerDay: 4500,
    pricePerHalfDay: 2800,
    amenities: ["wifi", "catering", "av_equipment", "accessibility", "natural_light"],
    images: [
      "https://images.unsplash.com/photo-1566127444979-b3d2b654e3d7?w=800",
      "https://images.unsplash.com/photo-1574958269340-fa927503f3dd?w=800",
      "https://images.unsplash.com/photo-1554907984-15263bfd63bd?w=800",
    ],
    venueType: "unique_venue",
    rating: 4.7,
    latitude: 52.3601,
    longitude: 4.8852,
    transportInfo: "Tram 2, 5, 12 stop at Museumplein. 5-minute walk from Van Baerlestraat. Amsterdam Centraal is 20 minutes by tram.",
    parkingInfo: "Q-Park Museumplein underground parking (2 min walk). €4/hour, €40/day max.",
    meetingExpertName: "Lisa Jansen",
    meetingExpertRole: "Events Manager",
    meetingExpertImage: expertImages[2],
    phoneNumber: "020 - 674 5000",
    email: "events@museum-eventhall.nl",
    sustainabilityInfo: "Historic building with modern energy-efficient climate systems. We donate 1% of event revenue to art restoration projects.",
    termsAndConditions: "No food or drinks near exhibition areas. Professional security required for events over 100 persons. Cancellation up to 30 days: full refund. 14-30 days: 50%. Less than 14 days: no refund.",
  },
  {
    name: "Spaces Herengracht",
    slug: "spaces-herengracht",
    city: "Amsterdam",
    address: "Herengracht 124, 1015 BT Amsterdam",
    description:
      "Modern co-working and meeting spaces in a historic canal house on the prestigious Herengracht. Combines Dutch heritage architecture with contemporary design. Flexible room sizes from intimate 4-person huddles to 50-person workshops. Complimentary barista coffee bar and networking lounge included.",
    shortDescription: "Modern meeting spaces in a historic canal house with barista coffee included",
    capacity: 50,
    pricePerDay: 650,
    pricePerHalfDay: 380,
    amenities: ["wifi", "projector", "whiteboard", "kitchen", "video_conferencing", "natural_light"],
    images: [
      "https://images.unsplash.com/photo-1497366811353-6870744d04b2?w=800",
      "https://images.unsplash.com/photo-1524758631624-e2822e304c36?w=800",
      "https://images.unsplash.com/photo-1527192491265-7e15c55b1ed2?w=800",
    ],
    venueType: "coworking",
    rating: 4.5,
    latitude: 52.3768,
    longitude: 4.8876,
    transportInfo: "8-minute walk from Amsterdam Centraal. Tram 1, 2, 5 stop at Nieuwezijds Kolk. Bus 18, 21, 22 nearby.",
    parkingInfo: "Street parking with permit. Nearest garage: Parking Centrum Oosterdok (10 min walk), €5/hour.",
    meetingExpertName: "Mark Bakker",
    meetingExpertRole: "Community Manager",
    meetingExpertImage: expertImages[3],
    phoneNumber: "020 - 261 5050",
    email: "herengracht@spaces.nl",
    sustainabilityInfo: "100% green energy. Complimentary organic fair-trade coffee. Bike parking for all guests.",
    termsAndConditions: "24-hour cancellation policy for rooms under 10 persons. 72 hours for larger bookings. No refund for no-shows. Building quiet hours after 22:00.",
  },
  {
    name: "SkyLounge Amsterdam",
    slug: "skylounge-amsterdam",
    city: "Amsterdam",
    address: "Oosterdoksstraat 4, 1011 DK Amsterdam",
    description:
      "Elevate your event at this spectacular rooftop venue with 360-degree views of Amsterdam's skyline. Located atop a luxury hotel near Central Station, the SkyLounge offers a sophisticated setting for cocktail receptions, networking events, and exclusive presentations. Indoor and outdoor terrace spaces available year-round.",
    shortDescription: "Spectacular rooftop venue with 360-degree Amsterdam skyline views",
    capacity: 80,
    pricePerDay: 2200,
    pricePerHalfDay: 1300,
    amenities: ["wifi", "catering", "av_equipment", "outdoor_space", "accessibility"],
    images: [
      "https://images.unsplash.com/photo-1519167758481-83f550bb49b3?w=800",
      "https://images.unsplash.com/photo-1470337458703-46ad1756a187?w=800",
      "https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?w=800",
    ],
    venueType: "unique_venue",
    rating: 4.6,
    latitude: 52.3808,
    longitude: 4.9015,
    transportInfo: "2-minute walk from Amsterdam Centraal station. All major tram, bus, and metro lines accessible.",
    parkingInfo: "Hotel valet parking available, €55/day. Public parking at Oosterdok, €5/hour.",
    meetingExpertName: "Eva Mulder",
    meetingExpertRole: "Events Director",
    meetingExpertImage: expertImages[4],
    phoneNumber: "020 - 530 2010",
    email: "events@skylounge-amsterdam.nl",
    sustainabilityInfo: "Rooftop herb garden supplies our kitchen. Low-energy LED mood lighting throughout.",
    termsAndConditions: "Outdoor terrace subject to weather conditions. Minimum spend of €2,000 for exclusive bookings. 14-day cancellation policy. Smart casual dress code required.",
  },
  {
    name: "Hotel V Nesplein",
    slug: "hotel-v-nesplein",
    city: "Amsterdam",
    address: "Nes 49, 1012 KD Amsterdam",
    description:
      "Boutique hotel meeting rooms in the heart of Amsterdam's theater district. Stylishly designed spaces with exposed brick, designer furniture, and a relaxed atmosphere. Ideal for workshops, team retreats, and strategy sessions. Overnight accommodation packages available for multi-day events. Restaurant on-site for working lunches.",
    shortDescription: "Boutique hotel meeting rooms in Amsterdam's vibrant theater district",
    capacity: 60,
    pricePerDay: 1200,
    pricePerHalfDay: 700,
    amenities: ["wifi", "catering", "projector", "whiteboard", "accessibility", "natural_light", "kitchen"],
    images: [
      "https://images.unsplash.com/photo-1517502884422-41eaead166d4?w=800",
      "https://images.unsplash.com/photo-1564069114553-7215e1ff1890?w=800",
      "https://images.unsplash.com/photo-1595576508898-0ad5c879a061?w=800",
    ],
    venueType: "hotel",
    rating: 4.4,
    latitude: 52.3712,
    longitude: 4.8944,
    transportInfo: "5-minute walk from Dam Square. Tram 4, 14, 24 stop at Rokin. Amsterdam Centraal 10 minutes on foot.",
    parkingInfo: "No on-site parking. Nearest: Parking de Bijenkorf (5 min walk), €5/hour. Bike rental available.",
    meetingExpertName: "Sophie van den Berg",
    meetingExpertRole: "Meeting & Events Coordinator",
    meetingExpertImage: expertImages[0],
    phoneNumber: "020 - 662 3233",
    email: "meetings@hotelv.nl",
    sustainabilityInfo: "Green Key Gold certified. Locally sourced restaurant menu. Energy-efficient building systems.",
    termsAndConditions: "Accommodation packages require 7-day advance booking. Meeting room cancellation: 48 hours notice for full refund. Restaurant reservations included with full-day bookings.",
  },

  // ROTTERDAM (4)
  {
    name: "De Rotterdam Conference Center",
    slug: "de-rotterdam-conference-center",
    city: "Rotterdam",
    address: "Wilhelminakade 177, 3072 AP Rotterdam",
    description:
      "A modern conference center in Rotterdam's iconic De Rotterdam building designed by Rem Koolhaas. Offering cutting-edge facilities with spectacular views over the Maas river and Erasmus Bridge. Multiple halls accommodate events from 50 to 400 guests. The venue reflects Rotterdam's innovative architectural spirit.",
    shortDescription: "Iconic Rem Koolhaas building with stunning Maas river and Erasmus Bridge views",
    capacity: 400,
    pricePerDay: 3200,
    pricePerHalfDay: 1900,
    amenities: ["wifi", "catering", "projector", "av_equipment", "breakout_rooms", "parking", "accessibility", "video_conferencing"],
    images: [
      "https://images.unsplash.com/photo-1497366216548-37526070297c?w=800",
      "https://images.unsplash.com/photo-1542744173-8e7e53415bb0?w=800",
      "https://images.unsplash.com/photo-1462826303086-329426d1aef5?w=800",
    ],
    venueType: "conference_center",
    rating: 4.7,
    latitude: 51.9066,
    longitude: 4.4856,
    transportInfo: "Wilhelminaplein metro station (2 min walk). Water taxi from Rotterdam Centraal. Tram 20, 25 stop nearby.",
    parkingInfo: "Underground parking, 150 spaces. €20/day. Electric vehicle charging points.",
    meetingExpertName: "Thomas de Groot",
    meetingExpertRole: "Conference Director",
    meetingExpertImage: expertImages[1],
    phoneNumber: "010 - 290 8400",
    email: "conferences@derotterdam-cc.nl",
    sustainabilityInfo: "BREEAM Excellent certified building. Rainwater recycling system. 100% LED lighting.",
    termsAndConditions: "Cancellation 21+ days: full refund. 7-21 days: 50%. Less than 7 days: no refund. Setup time: 2 hours before event included. Technical support staff included.",
  },
  {
    name: "Maaskant Vergaderzalen",
    slug: "maaskant-vergaderzalen",
    city: "Rotterdam",
    address: "Boompjes 40, 3011 XB Rotterdam",
    description:
      "Intimate meeting rooms with breathtaking views of the Erasmus Bridge and Maas river. Each room features floor-to-ceiling windows, ergonomic furniture, and the latest presentation technology. Perfect for board meetings, client presentations, and strategic planning sessions. Located in Rotterdam's financial district.",
    shortDescription: "Intimate meeting rooms with breathtaking Erasmus Bridge views",
    capacity: 40,
    pricePerDay: 550,
    pricePerHalfDay: 320,
    amenities: ["wifi", "projector", "whiteboard", "video_conferencing", "natural_light", "accessibility"],
    images: [
      "https://images.unsplash.com/photo-1600880292203-757bb62b4baf?w=800",
      "https://images.unsplash.com/photo-1604328698692-f76ea9498e76?w=800",
      "https://images.unsplash.com/photo-1568992687947-868a62a9f521?w=800",
    ],
    venueType: "meeting_room",
    rating: 4.3,
    latitude: 51.9173,
    longitude: 4.4901,
    transportInfo: "Rotterdam Blaak station (5 min walk). Metro A, B, C to Blaak. Bus 32, 44 stop at Boompjes.",
    parkingInfo: "Street parking limited. Parking Markthal (3 min walk), €3.50/hour.",
    meetingExpertName: "Anja Visser",
    meetingExpertRole: "Office Manager",
    meetingExpertImage: expertImages[2],
    phoneNumber: "010 - 411 3500",
    email: "info@maaskant-vergaderzalen.nl",
    sustainabilityInfo: "Paperless office initiative. Energy-efficient climate control. Green cleaning products.",
    termsAndConditions: "24-hour cancellation for small rooms. 72 hours for rooms over 20 persons. Complimentary coffee and tea included. Lunch packages available from €15/person.",
  },
  {
    name: "Fenix Creative Studio",
    slug: "fenix-creative-studio",
    city: "Rotterdam",
    address: "Veerlaan 19D, 3072 AN Rotterdam",
    description:
      "A creative workshop space in Rotterdam's trendy Katendrecht neighborhood, housed in the renovated Fenix warehouse. Raw industrial aesthetics meet modern comfort with exposed steel beams, polished concrete floors, and abundant natural light. Ideal for design thinking workshops, hackathons, and innovation sprints.",
    shortDescription: "Industrial-chic creative space in Rotterdam's trendy Katendrecht warehouse district",
    capacity: 70,
    pricePerDay: 950,
    pricePerHalfDay: 550,
    amenities: ["wifi", "whiteboard", "kitchen", "natural_light", "breakout_rooms", "outdoor_space"],
    images: [
      "https://images.unsplash.com/photo-1504384308090-c894fdcc538d?w=800",
      "https://images.unsplash.com/photo-1517502884422-41eaead166d4?w=800",
      "https://images.unsplash.com/photo-1573164713988-8665fc963095?w=800",
    ],
    venueType: "workshop_space",
    rating: 4.6,
    latitude: 51.9014,
    longitude: 4.4862,
    transportInfo: "Water taxi from Hotel New York. Tram 20 to Katendrecht. 15 minutes from Rotterdam Centraal by public transport.",
    parkingInfo: "Free street parking available. Limited spaces. Bike parking for 50+ bikes.",
    meetingExpertName: "Bas Hendriks",
    meetingExpertRole: "Creative Director",
    meetingExpertImage: expertImages[3],
    phoneNumber: "010 - 785 2200",
    email: "create@fenix-studio.nl",
    sustainabilityInfo: "Repurposed industrial building. Local food trucks for catering. Bike-friendly location.",
    termsAndConditions: "48-hour cancellation policy. Own catering welcome (kitchen available). Noise permitted until 22:00. Basic cleaning included, deep clean €200 extra.",
  },
  {
    name: "Van Nelle Fabriek Loft",
    slug: "van-nelle-fabriek-loft",
    city: "Rotterdam",
    address: "Van Nelleweg 1, 3044 BC Rotterdam",
    description:
      "UNESCO World Heritage industrial venue in the iconic Van Nelle Factory. This 1920s masterpiece of modern architecture offers vast open spaces with original factory windows flooding the rooms with light. A truly unique setting for conferences, exhibitions, and corporate celebrations that demand architectural distinction.",
    shortDescription: "UNESCO World Heritage industrial masterpiece with vast light-filled spaces",
    capacity: 180,
    pricePerDay: 2800,
    pricePerHalfDay: 1700,
    amenities: ["wifi", "catering", "av_equipment", "parking", "natural_light", "accessibility", "outdoor_space"],
    images: [
      "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800",
      "https://images.unsplash.com/photo-1504384764586-bb4cdc1707b0?w=800",
      "https://images.unsplash.com/photo-1497215842964-222b430dc094?w=800",
    ],
    venueType: "unique_venue",
    rating: 4.8,
    latitude: 51.9297,
    longitude: 4.4363,
    transportInfo: "Bus 38 from Rotterdam Centraal (15 min). Limited public transport; taxi recommended. 10 minutes by car from city center.",
    parkingInfo: "Large on-site parking lot, 300 spaces. Free for event guests.",
    meetingExpertName: "Marloes Kuiper",
    meetingExpertRole: "Heritage Events Manager",
    meetingExpertImage: expertImages[4],
    phoneNumber: "010 - 262 0300",
    email: "events@vannellefabriek.nl",
    sustainabilityInfo: "UNESCO World Heritage site with sustainable restoration. Solar panels on original factory roof. Rainwater collection for gardens.",
    termsAndConditions: "Heritage building regulations apply. No fixtures on walls or original surfaces. 21-day cancellation policy. Professional event crew required for events 100+. Insurance certificate required.",
  },

  // UTRECHT (3)
  {
    name: "Landgoed Oud-Amelisweerd",
    slug: "landgoed-oud-amelisweerd",
    city: "Utrecht",
    address: "Koningslaan 11, 3981 HD Bunnik",
    description:
      "A stunning 18th-century country estate surrounded by ancient forests just outside Utrecht. The estate offers elegant rooms with period details, gardens for outdoor breaks, and a tranquil setting that inspires focused thinking. Perfect for executive retreats, leadership offsites, and multi-day strategy sessions. On-site accommodation available.",
    shortDescription: "Elegant 18th-century estate surrounded by ancient forests near Utrecht",
    capacity: 120,
    pricePerDay: 2200,
    pricePerHalfDay: 1300,
    amenities: ["wifi", "catering", "projector", "breakout_rooms", "parking", "natural_light", "outdoor_space", "kitchen"],
    images: [
      "https://images.unsplash.com/photo-1464146072230-91cabc968266?w=800",
      "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800",
      "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=800",
    ],
    venueType: "unique_venue",
    rating: 4.7,
    latitude: 52.0644,
    longitude: 5.1832,
    transportInfo: "Bus 41 from Utrecht Centraal to Bunnik (20 min). 10-minute drive from A12 highway. Shuttle service available on request.",
    parkingInfo: "Ample free parking on the estate grounds. 80+ spaces. Coach parking available.",
    meetingExpertName: "Willem van Dijk",
    meetingExpertRole: "Estate Manager",
    meetingExpertImage: expertImages[1],
    phoneNumber: "030 - 656 1800",
    email: "events@oud-amelisweerd.nl",
    sustainabilityInfo: "Estate managed with biodiversity in mind. Local seasonal catering from estate gardens. Heat pump and solar energy systems.",
    termsAndConditions: "14-day cancellation for full refund. Multi-day bookings require 30-day notice. Outdoor events weather-dependent. Estate walks included for attendees. No smoking indoors.",
  },
  {
    name: "Academiegebouw Utrecht",
    slug: "academiegebouw-utrecht",
    city: "Utrecht",
    address: "Domplein 29, 3512 JE Utrecht",
    description:
      "The historic University of Utrecht's Academy Building on the Domplein, next to the famous Dom Tower. This prestigious venue combines academic gravitas with modern event facilities. Grand halls with ornate ceilings and chandeliers create an impressive backdrop for conferences, symposiums, and award ceremonies.",
    shortDescription: "Historic university building next to the iconic Dom Tower on Domplein",
    capacity: 250,
    pricePerDay: 1900,
    pricePerHalfDay: 1100,
    amenities: ["wifi", "catering", "av_equipment", "accessibility", "natural_light", "projector"],
    images: [
      "https://images.unsplash.com/photo-1594122230689-45899d9e6f69?w=800",
      "https://images.unsplash.com/photo-1571624436279-b272aff752b5?w=800",
      "https://images.unsplash.com/photo-1513475382585-d06e58bcb0e0?w=800",
    ],
    venueType: "conference_center",
    rating: 4.5,
    latitude: 52.0856,
    longitude: 5.1193,
    transportInfo: "10-minute walk from Utrecht Centraal station. Bus 2 to Domplein. City center location accessible by all public transport.",
    parkingInfo: "No on-site parking. Springweg parking garage (5 min walk), €3/hour. Janskerkhof parking (3 min walk).",
    meetingExpertName: "Dr. Irene Bakker",
    meetingExpertRole: "Academic Events Coordinator",
    meetingExpertImage: expertImages[2],
    phoneNumber: "030 - 253 2020",
    email: "academiegebouw@uu.nl",
    sustainabilityInfo: "Utrecht University sustainability commitment. Carbon-neutral events program. Digital conference materials preferred.",
    termsAndConditions: "Academic events receive 15% discount. 21-day cancellation policy. No alterations to historic interior. Technical crew provided. Rehearsal time available day before.",
  },
  {
    name: "Seats2meet Utrecht CS",
    slug: "seats2meet-utrecht-cs",
    city: "Utrecht",
    address: "Moreelsepark 65, 3511 EP Utrecht",
    description:
      "Modern, flexible meeting rooms steps from Utrecht Central Station. This innovative venue concept offers pay-per-use meeting spaces with a vibrant co-working community. Quick setup, professional facilities, and an energetic atmosphere. Ideal for client meetings, workshops, and team gatherings when accessibility is key.",
    shortDescription: "Flexible meeting rooms steps from Utrecht Central Station",
    capacity: 35,
    pricePerDay: 420,
    pricePerHalfDay: 250,
    amenities: ["wifi", "projector", "whiteboard", "video_conferencing", "kitchen", "accessibility"],
    images: [
      "https://images.unsplash.com/photo-1497215842964-222b430dc094?w=800",
      "https://images.unsplash.com/photo-1527192491265-7e15c55b1ed2?w=800",
      "https://images.unsplash.com/photo-1524758631624-e2822e304c36?w=800",
    ],
    venueType: "coworking",
    rating: 4.2,
    latitude: 52.0894,
    longitude: 5.1107,
    transportInfo: "Directly adjacent to Utrecht Centraal station. 1-minute walk. All national and international train connections.",
    parkingInfo: "Jaarbeurs parking (2 min walk), €2.50/hour. P+R Science Park recommended for day visitors.",
    meetingExpertName: "Nina de Jong",
    meetingExpertRole: "Community Host",
    meetingExpertImage: expertImages[4],
    phoneNumber: "030 - 307 3700",
    email: "utrecht@seats2meet.com",
    sustainabilityInfo: "Shared economy model reduces resource waste. Vegetarian catering default. Bike-first accessibility.",
    termsAndConditions: "Free cancellation up to 24 hours. No-show fee applies. Complimentary coffee/tea/water. Lunch orders before 10:00 same day.",
  },

  // THE HAGUE (4)
  {
    name: "Nieuwspoort Perscentrum",
    slug: "nieuwspoort-perscentrum",
    city: "The Hague",
    address: "Lange Poten 10, 2511 CL Den Haag",
    description:
      "The Netherlands' most prestigious press and conference center, located adjacent to the Binnenhof and Dutch parliament. A venue steeped in political history, favored by government organizations, NGOs, and international institutions. Professional event support, high security standards, and excellent public transport access.",
    shortDescription: "Prestigious press center adjacent to the Binnenhof and Dutch parliament",
    capacity: 350,
    pricePerDay: 2800,
    pricePerHalfDay: 1700,
    amenities: ["wifi", "catering", "projector", "av_equipment", "breakout_rooms", "accessibility", "video_conferencing"],
    images: [
      "https://images.unsplash.com/photo-1505373877841-8d25f7d46678?w=800",
      "https://images.unsplash.com/photo-1560439513-74b037a25d84?w=800",
      "https://images.unsplash.com/photo-1551818255-e6e10975bc17?w=800",
    ],
    venueType: "conference_center",
    rating: 4.6,
    latitude: 52.0799,
    longitude: 4.3131,
    transportInfo: "5-minute walk from Den Haag Centraal. Tram 1, 9 to Binnenhof stop. Direct Intercity connections to Amsterdam/Rotterdam.",
    parkingInfo: "Parking Malieveld (5 min walk), €2.50/hour. Limited street parking. Bike parking at entrance.",
    meetingExpertName: "Robert Smits",
    meetingExpertRole: "Conference Manager",
    meetingExpertImage: expertImages[3],
    phoneNumber: "070 - 346 9640",
    email: "info@nieuwspoort.nl",
    sustainabilityInfo: "Green events certification. Digital-first conference materials. Sustainable catering options standard.",
    termsAndConditions: "Security clearance may be required for certain rooms. 14-day cancellation policy. Press facilities available. Simultaneous interpretation booths available. Technical rehearsal included.",
  },
  {
    name: "Beachclub Naturel Scheveningen",
    slug: "beachclub-naturel-scheveningen",
    city: "The Hague",
    address: "Strandweg 33, 2586 JK Scheveningen",
    description:
      "A unique beachfront venue on the Scheveningen coast with panoramic North Sea views. This modern beach club offers both indoor meeting spaces and a stunning outdoor terrace. The sound of waves and sea air create an energizing atmosphere for team events, summer conferences, and corporate celebrations.",
    shortDescription: "Beachfront venue with panoramic North Sea views on the Scheveningen coast",
    capacity: 100,
    pricePerDay: 1600,
    pricePerHalfDay: 950,
    amenities: ["wifi", "catering", "av_equipment", "outdoor_space", "parking", "natural_light", "kitchen"],
    images: [
      "https://images.unsplash.com/photo-1540541338287-41700207dee6?w=800",
      "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800",
      "https://images.unsplash.com/photo-1445019980597-93fa8acb246c?w=800",
    ],
    venueType: "unique_venue",
    rating: 4.4,
    latitude: 52.1072,
    longitude: 4.2744,
    transportInfo: "Tram 1 from Den Haag Centraal to Scheveningen (20 min). Bus 22, 23 to Strandweg. Train to Den Haag HS then tram.",
    parkingInfo: "Zwarte Pad parking lot (2 min walk), €8/day. Beach boulevard parking, €3/hour in summer.",
    meetingExpertName: "Carmen van Leeuwen",
    meetingExpertRole: "Beach Events Coordinator",
    meetingExpertImage: expertImages[0],
    phoneNumber: "070 - 306 3700",
    email: "events@beachclub-naturel.nl",
    sustainabilityInfo: "Beach cleanup program with every event. Seasonal local seafood menu. Biodegradable serviceware.",
    termsAndConditions: "Outdoor events weather-dependent. Indoor backup space available. 7-day cancellation for full refund. Minimum spend applies in summer months (Jun-Aug). Sunset slots available Apr-Sep.",
  },
  {
    name: "Pulchri Studio",
    slug: "pulchri-studio",
    city: "The Hague",
    address: "Lange Voorhout 15, 2514 EA Den Haag",
    description:
      "An artists' society and gallery on the elegant Lange Voorhout boulevard, one of The Hague's most beautiful locations. Art-filled rooms with high ceilings, chandeliers, and garden views provide an inspiring setting for creative workshops, networking events, and cultural gatherings. Combine your event with a private exhibition viewing.",
    shortDescription: "Art-filled gallery on The Hague's most elegant boulevard",
    capacity: 80,
    pricePerDay: 1650,
    pricePerHalfDay: 1000,
    amenities: ["wifi", "catering", "natural_light", "accessibility", "outdoor_space"],
    images: [
      "https://images.unsplash.com/photo-1574958269340-fa927503f3dd?w=800",
      "https://images.unsplash.com/photo-1554907984-15263bfd63bd?w=800",
      "https://images.unsplash.com/photo-1513475382585-d06e58bcb0e0?w=800",
    ],
    venueType: "unique_venue",
    rating: 4.5,
    latitude: 52.0833,
    longitude: 4.3127,
    transportInfo: "Tram 1 to Kneuterdijk (1 min walk). 10-minute walk from Den Haag Centraal. On the Lange Voorhout boulevard.",
    parkingInfo: "Parking Malieveld (5 min walk). Museumkwartier parking (3 min walk), €3/hour. Limited street parking.",
    meetingExpertName: "Femke Mostert",
    meetingExpertRole: "Cultural Events Manager",
    meetingExpertImage: expertImages[2],
    phoneNumber: "070 - 346 1735",
    email: "events@pulchri.nl",
    sustainabilityInfo: "Historic building carefully maintained. 5% of event proceeds support emerging artists. Local organic catering.",
    termsAndConditions: "Art handling protocols must be followed. No fixtures on walls. Professional photography included in full-day bookings. 14-day cancellation policy. Evening events until 23:00.",
  },
  {
    name: "Regus World Forum",
    slug: "regus-world-forum",
    city: "The Hague",
    address: "Churchillplein 10, 2517 JW Den Haag",
    description:
      "Professional business center in the iconic World Forum complex, the venue for major international conferences. Flexible meeting rooms with global-standard facilities, ideal for international business meetings, training sessions, and client presentations. Surrounded by embassies and international organizations.",
    shortDescription: "Professional business center in the iconic World Forum complex",
    capacity: 45,
    pricePerDay: 580,
    pricePerHalfDay: 340,
    amenities: ["wifi", "projector", "whiteboard", "video_conferencing", "parking", "accessibility"],
    images: [
      "https://images.unsplash.com/photo-1568992687947-868a62a9f521?w=800",
      "https://images.unsplash.com/photo-1497366216548-37526070297c?w=800",
      "https://images.unsplash.com/photo-1604328698692-f76ea9498e76?w=800",
    ],
    venueType: "meeting_room",
    rating: 4.1,
    latitude: 52.0935,
    longitude: 4.2833,
    transportInfo: "Tram 9 to World Forum stop. Bus 24 from Den Haag Centraal. 15-minute walk from Den Haag HS station.",
    parkingInfo: "World Forum underground parking, €15/day. EV charging available.",
    meetingExpertName: "Paul Vermeer",
    meetingExpertRole: "Business Center Manager",
    meetingExpertImage: expertImages[1],
    phoneNumber: "070 - 352 0100",
    email: "worldforum@regus.nl",
    sustainabilityInfo: "Regus global sustainability program. Shared resources reduce per-meeting footprint.",
    termsAndConditions: "Flexible hourly and daily rates. 24-hour cancellation. Virtual office address available. Mail handling services. Receptionist included.",
  },

  // EINDHOVEN (3)
  {
    name: "High Tech Campus Conference Center",
    slug: "high-tech-campus-conference-center",
    city: "Eindhoven",
    address: "High Tech Campus 1, 5656 AE Eindhoven",
    description:
      "State-of-the-art conference facilities in the heart of Brainport Eindhoven, Europe's leading technology hub. Known as 'the smartest square kilometer in Europe,' this venue offers cutting-edge tech infrastructure, innovation showcases, and networking with 12,000+ tech professionals on campus. Perfect for tech conferences, product demos, and innovation summits.",
    shortDescription: "Conference center in 'the smartest square kilometer in Europe'",
    capacity: 220,
    pricePerDay: 2200,
    pricePerHalfDay: 1300,
    amenities: ["wifi", "catering", "projector", "av_equipment", "breakout_rooms", "parking", "accessibility", "video_conferencing"],
    images: [
      "https://images.unsplash.com/photo-1497366216548-37526070297c?w=800",
      "https://images.unsplash.com/photo-1542744173-8e7e53415bb0?w=800",
      "https://images.unsplash.com/photo-1505373877841-8d25f7d46678?w=800",
    ],
    venueType: "conference_center",
    rating: 4.7,
    latitude: 51.4109,
    longitude: 5.4596,
    transportInfo: "Free shuttle bus from Eindhoven Centraal (every 10 min). Bus 407, 408 to High Tech Campus. A2/A67 highway exit directly to campus.",
    parkingInfo: "Extensive free parking on campus. Over 5,000 spaces. EV charging throughout.",
    meetingExpertName: "Sander Janssen",
    meetingExpertRole: "Tech Events Director",
    meetingExpertImage: expertImages[3],
    phoneNumber: "040 - 277 0100",
    email: "events@hightechcampus.com",
    sustainabilityInfo: "Campus-wide sustainability program. Green energy from on-site solar. Innovative climate systems. Bike-sharing program.",
    termsAndConditions: "Campus access badge required. 14-day cancellation policy. Demo rooms available for product showcases. NDA-ready secure meeting rooms available. Innovation tour included for full-day bookings.",
  },
  {
    name: "Kazerne Design Experience",
    slug: "kazerne-design-experience",
    city: "Eindhoven",
    address: "Paradijslaan 2-8, 5611 KN Eindhoven",
    description:
      "A design-forward event venue in a former military barracks, now a cultural hotspot during Dutch Design Week. Exhibition spaces, a fine-dining restaurant, and curated design installations create an atmosphere of creative excellence. Perfect for brand launches, design thinking workshops, and events where aesthetics matter.",
    shortDescription: "Design-forward venue in former military barracks, a Dutch Design Week hotspot",
    capacity: 90,
    pricePerDay: 1500,
    pricePerHalfDay: 900,
    amenities: ["wifi", "catering", "natural_light", "outdoor_space", "accessibility", "kitchen"],
    images: [
      "https://images.unsplash.com/photo-1524758631624-e2822e304c36?w=800",
      "https://images.unsplash.com/photo-1504384764586-bb4cdc1707b0?w=800",
      "https://images.unsplash.com/photo-1517502884422-41eaead166d4?w=800",
    ],
    venueType: "unique_venue",
    rating: 4.6,
    latitude: 51.4377,
    longitude: 5.4767,
    transportInfo: "10-minute walk from Eindhoven Centraal. Bus 6, 7 to Paradijslaan. City center location.",
    parkingInfo: "Parking Heuvel (5 min walk), €2.50/hour. Limited street parking. Bike parking at entrance.",
    meetingExpertName: "Lotte Peeters",
    meetingExpertRole: "Experience Curator",
    meetingExpertImage: expertImages[4],
    phoneNumber: "040 - 235 0600",
    email: "events@kazerne.com",
    sustainabilityInfo: "Restaurant uses zero-waste cooking philosophy. Local Dutch Design products throughout. Sustainable renovation of heritage building.",
    termsAndConditions: "During Dutch Design Week (October), premium rates apply. 7-day cancellation policy. Fine dining packages available. Exhibition inclusion subject to current program. Photography permitted.",
  },
  {
    name: "Strijp-S Event Hall",
    slug: "strijp-s-event-hall",
    city: "Eindhoven",
    address: "Torenallee 22-04, 5617 BD Eindhoven",
    description:
      "A versatile event space in Eindhoven's vibrant Strijp-S district, the former Philips industrial complex transformed into a creative quarter. High ceilings, industrial charm, and adaptable floor plans make this venue suitable for everything from corporate workshops to large-scale exhibitions. The surrounding area offers restaurants, galleries, and urban culture.",
    shortDescription: "Versatile industrial event space in Eindhoven's creative Strijp-S quarter",
    capacity: 180,
    pricePerDay: 1800,
    pricePerHalfDay: 1050,
    amenities: ["wifi", "catering", "av_equipment", "parking", "breakout_rooms", "natural_light", "whiteboard"],
    images: [
      "https://images.unsplash.com/photo-1504384308090-c894fdcc538d?w=800",
      "https://images.unsplash.com/photo-1462826303086-329426d1aef5?w=800",
      "https://images.unsplash.com/photo-1590523741831-ab7e8b8f9c7f?w=800",
    ],
    venueType: "workshop_space",
    rating: 4.4,
    latitude: 51.4485,
    longitude: 5.4524,
    transportInfo: "Bus 401 from Eindhoven Centraal to Strijp-S (10 min). 15-minute walk from station. Near A2/A58 highway.",
    parkingInfo: "Strijp-S parking garage, €1.50/hour, €10/day max. Street parking available evenings/weekends.",
    meetingExpertName: "Rick van Oosterom",
    meetingExpertRole: "Venue Coordinator",
    meetingExpertImage: expertImages[0],
    phoneNumber: "040 - 294 6800",
    email: "events@strijps-eventhall.nl",
    sustainabilityInfo: "Industrial heritage building with modern energy systems. Food truck catering reduces food waste. Urban gardening project on premises.",
    termsAndConditions: "Flexible floor plans; setup consultation included. 7-day cancellation for full refund. Noise levels monitored (residential area). Loading dock available. Own decorations permitted with approval.",
  },
];

async function main() {
  console.log("Seeding database with 20 Dutch venues...");

  await prisma.venue.deleteMany();
  await prisma.booking.deleteMany();

  for (const venue of venues) {
    const amenities = venue.amenities;
    await prisma.venue.create({
      data: {
        name: venue.name,
        slug: venue.slug,
        city: venue.city,
        address: venue.address,
        description: venue.description,
        shortDescription: venue.shortDescription,
        capacity: venue.capacity,
        pricePerDay: venue.pricePerDay,
        pricePerHalfDay: venue.pricePerHalfDay,
        amenities: JSON.stringify(amenities),
        images: JSON.stringify(venue.images),
        venueType: venue.venueType,
        rating: venue.rating,
        latitude: venue.latitude,
        longitude: venue.longitude,
        facilities: makeFacilities(amenities),
        roomLayouts: makeRoomLayouts(venue.capacity, venue.venueType),
        transportInfo: venue.transportInfo,
        parkingInfo: venue.parkingInfo,
        termsAndConditions: venue.termsAndConditions,
        sustainabilityInfo: venue.sustainabilityInfo,
        meetingExpertName: venue.meetingExpertName,
        meetingExpertRole: venue.meetingExpertRole,
        meetingExpertImage: venue.meetingExpertImage,
        phoneNumber: venue.phoneNumber,
        email: venue.email,
        status: "approved",
        isAiGenerated: false,
      },
    });
  }

  const count = await prisma.venue.count();
  console.log(`Seeded ${count} venues successfully.`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
